services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app        # sync local files
      - /app/node_modules     # prevent overwriting node_modules
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      