services:
  backend:
    build: ./backend
    # bind only what’s needed for dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/package.json:/app/package.json
      - backend_node_modules:/app/node_modules    # container-only deps
      - ./backend/data:/app/data                  # persist DB
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/package.json:/app/package.json
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  backend_node_modules:
  frontend_node_modules:
