CREATE TABLE IF NOT EXISTS items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  qty INTEGER NOT NULL DEFAULT 0
);

INSERT INTO items (name, qty) VALUES ('Apple', 10)
  ON CONFLICT DO NOTHING;
